name: Shrine
description: Learn how to use Material for structure and layout.

dependencies:
  #  carousel_slider: ^1.3.0
  #  charts_flutter: ^0.6.0
  #  charts_common: ^0.6.0
  #  collection: ^1.14.5
  meta: ^1.1.1
  flutter_rating: ^0.0.2
  intl: ^0.15.8
  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

  firebase_auth: 0.7.0
  google_sign_in: 3.2.4
  firebase_core: ^0.2.5  # add dependency for Firebase Core
  cloud_firestore: 0.8.2+3        # new
  #  cloud_firestore: 0.8.0        # new
  firebase_storage: 1.0.4
  image_picker: 0.4.12+1
  uuid: ^1.0.0
  http: ^0.12.0

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/mainImage_temp.jpg
  - assets/burger.jpg
  - packages/shrine_images/0-0.jpg
  - packages/shrine_images/1-0.jpg
  - packages/shrine_images/2-0.jpg
  - packages/shrine_images/3-0.jpg
  - packages/shrine_images/4-0.jpg
  - packages/shrine_images/5-0.jpg
  - packages/shrine_images/6-0.jpg
  - packages/shrine_images/7-0.jpg
  - packages/shrine_images/8-0.jpg
  - packages/shrine_images/9-0.jpg
  - packages/shrine_images/10-0.jpg
  - packages/shrine_images/11-0.jpg
  - packages/shrine_images/12-0.jpg
  - packages/shrine_images/13-0.jpg
  - packages/shrine_images/14-0.jpg
  - packages/shrine_images/15-0.jpg
  - packages/shrine_images/16-0.jpg
  - packages/shrine_images/17-0.jpg
  - packages/shrine_images/18-0.jpg
  - packages/shrine_images/19-0.jpg
  - packages/shrine_images/20-0.jpg
  - packages/shrine_images/21-0.jpg
  - packages/shrine_images/22-0.jpg
  - packages/shrine_images/23-0.jpg
  - packages/shrine_images/24-0.jpg
  - packages/shrine_images/25-0.jpg
  - packages/shrine_images/26-0.jpg
  - packages/shrine_images/27-0.jpg
  - packages/shrine_images/28-0.jpg
  - packages/shrine_images/29-0.jpg
  - packages/shrine_images/30-0.jpg
  - packages/shrine_images/31-0.jpg
  - packages/shrine_images/32-0.jpg
  - packages/shrine_images/33-0.jpg
  - packages/shrine_images/34-0.jpg
  - packages/shrine_images/35-0.jpg
  - packages/shrine_images/36-0.jpg
  - packages/shrine_images/37-0.jpg
