name: Shrine
description: Learn how to use Material for structure and layout.

dependencies:
  #  carousel_slider: ^1.3.0
  #  charts_flutter: ^0.6.0
  #  charts_common: ^0.6.0
  #  collection: ^1.14.5
  meta: ^1.1.1
  flutter_rating: ^0.0.2
  intl: ^0.15.8
  cupertino_icons: ^0.1.0
  shrine_images: 1.1.1

  firebase_auth: 0.7.0
  google_sign_in: 3.2.4
  firebase_core: ^0.2.5  # add dependency for Firebase Core
  cloud_firestore: 0.8.2+3        # new
  #  cloud_firestore: 0.8.0        # new
  firebase_storage: 1.0.4
  image_picker: 0.4.12+1
  uuid: ^1.0.0
  http: ^0.12.0

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/mainImage_temp.jpg
  - assets/burger.jpg
  - assets/steak.jpg
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf